#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""WC26 Predictions — English static site generator (home + 12 groups + 72 match pages)."""
import json, os, shutil, html
from datetime import date

ROOT = os.path.dirname(os.path.abspath(__file__))
DIST = os.path.join(ROOT, "dist")
DATA = json.load(open(os.path.join(ROOT, "data", "groups.json"), encoding="utf-8"))
_meta_path = os.path.join(ROOT, "data", "meta.json")
META = json.load(open(_meta_path, encoding="utf-8")) if os.path.exists(_meta_path) else {}
TODAY = "2026-06-11"
BASE = "https://oraclexi.com"
SITE = "OracleXI"
# 填入 AdSense 发布商ID(形如 ca-pub-1234567890123456)后，自动广告脚本会注入全站 <head>，并生成 ads.txt
ADSENSE_PUB = os.environ.get("ADSENSE_PUB", "")
DESC = "AI predictions for all 104 matches of the 2026 FIFA World Cup — score predictions, win probabilities and expert analysis for every fixture across all 12 groups."

MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
WK = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
def fmt_date(d):
    if not d: return "TBD"
    y,m,dd = map(int, d.split("-"))
    return f"{WK[date(y,m,dd).weekday()]}, {MONTHS[m-1]} {dd}"

def esc(s): return html.escape(str(s)) if s else ""

def adsense_head():
    if not ADSENSE_PUB: return "<!-- AD_HEAD_SLOT -->"
    return (f'<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'
            f'?client={ADSENSE_PUB}" crossorigin="anonymous"></script>')

ALL = []
for L in "ABCDEFGHIJKL":
    for m in DATA[L]["matches"]:
        ALL.append(m)
ALL.sort(key=lambda m:(m["date"] or "9999", m.get("match_no") or 0))

def mslug(m): return f"{m['group'].lower()}{m['match_no']}"
def murl(m): return f"match/{mslug(m)}.html"
def P(m): return m.get("pred_en", {})

def head(title, desc, rel="", canon=""):
    return f"""<!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(desc)}">
<link rel="canonical" href="{BASE}/{canon}">
<meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(desc)}">
<meta property="og:type" content="website"><meta name="twitter:card" content="summary_large_image">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Sora:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{rel}style.css">
<link rel="icon" href="{rel}favicon.svg" type="image/svg+xml">
{adsense_head()}
</head><body>
<header class="nav"><div class="wrap">
<a class="brand" href="{rel}index.html"><span class="mark"><span>XI</span></span> OracleXI</a>
<nav><a href="{rel}index.html">Home</a><a href="{rel}index.html#fixtures">Fixtures</a><a href="{rel}index.html#groups">Groups</a><a href="{rel}index.html#upcoming">Predictions</a></nav>
</div></header>"""

def foot(rel=""):
    return f"""<footer><div class="wrap">
<div>© 2026 OracleXI · Data from public schedules · Predictions generated by AI for entertainment only</div>
<div><a href="{rel}index.html">Home</a> · <a href="{rel}about.html">About</a> · <a href="{rel}privacy.html">Privacy</a></div>
</div></footer>
<script>
const io=new IntersectionObserver((es)=>es.forEach(e=>{{if(e.isIntersecting){{e.target.style.animationDelay=(e.target.dataset.d||0)+'ms';e.target.classList.add('fade');io.unobserve(e.target)}}}}),{{threshold:.08}});
document.querySelectorAll('[data-reveal]').forEach((el,i)=>{{el.dataset.d=(i%6)*60;io.observe(el)}});
</script></body></html>"""

def ad(): return '<div class="ad-slot"><!-- AD_SLOT -->Advertisement</div>'

def accuracy_strip():
    if not META.get("played"): return ""
    return (f'<div class="acc-strip"><span><b>{META["played"]}</b>/72 played</span>'
            f'<span>Outcome accuracy <b>{META.get("outcome_acc","–")}%</b></span>'
            f'<span>Exact score <b>{META.get("score_acc","–")}%</b></span>'
            f'<span class="upd">Updated {esc(META.get("updated_utc",""))}</span></div>')

def standings_table(g):
    st = g.get("standings") or []
    if not any(r["P"] for r in st): return ""
    rows = "".join(
        f'<tr><td class="pos">{i+1}</td><td class="tm">{esc(r["team"])}</td>'
        f'<td>{r["P"]}</td><td>{r["W"]}</td><td>{r["D"]}</td><td>{r["L"]}</td>'
        f'<td>{r["GF"]}:{r["GA"]}</td><td class="pts">{r["Pts"]}</td></tr>'
        for i,r in enumerate(st))
    return (f'<div class="sec-head"><span class="idx">#</span><h2 class="disp">Standings</h2><div class="line"></div></div>'
            f'<table class="standings"><thead><tr><th>#</th><th>Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GF:GA</th><th>Pts</th></tr></thead><tbody>{rows}</tbody></table>')

def probs(m):
    p=P(m); w=p.get("win") or 0; d=p.get("draw") or 0; l=p.get("lose") or 0
    t=(w+d+l) or 1; return w/t*100, d/t*100, l/t*100

def result_badge(m):
    r = m.get("result")
    if not r or not r.get("played"): return ""
    p = P(m); ps = p.get("score","")
    pm = __import__("re").match(r"(\d+)-(\d+)", ps or "")
    hit = ""
    if pm:
        po = "h" if int(pm.group(1))>int(pm.group(2)) else ("a" if int(pm.group(1))<int(pm.group(2)) else "d")
        ao = "h" if r["hs"]>r["as"] else ("a" if r["hs"]<r["as"] else "d")
        hit = ' <span class="hit ok">✓ called</span>' if po==ao else ' <span class="hit no">✗ missed</span>'
    return f'<span class="ft">FT {r["hs"]}–{r["as"]}{hit}</span>'

def match_card(m, rel=""):
    w,d,l = probs(m); p=P(m)
    return f"""<a class="mcard" href="{rel}{murl(m)}" data-reveal>
<div class="top"><span class="grp">Group {m['group']} · Match {m.get('match_no','')}</span><span>{result_badge(m) or fmt_date(m['date'])}</span></div>
<div class="fixture"><div class="t">{esc(m['home'])}</div><div class="sc">{esc(p.get('score','-'))}</div><div class="t away">{esc(m['away'])}</div></div>
<div class="bar"><i class="w" style="width:{w:.0f}%"></i><i class="d" style="width:{d:.0f}%"></i><i class="l" style="width:{l:.0f}%"></i></div>
<div class="barlbl"><span>1 {w:.0f}%</span><span>X {d:.0f}%</span><span>2 {l:.0f}%</span></div>
<div class="ana">{esc(p.get('analysis',''))}</div>
</a>"""

def build_index():
    opener = DATA["A"]["matches"][0]; op = P(opener)
    upcoming = [m for m in ALL if (m["date"] or "") >= TODAY][:12]
    groups_html=""
    for L in "ABCDEFGHIJKL":
        lis="".join(f'<li><span class="seed">{i+1}</span>{esc(t["en"])}</li>' for i,t in enumerate(DATA[L]["teams"]))
        groups_html+=f'<a class="gcard" href="group/{L}.html" data-reveal><div class="gh"><div class="gl">{L}</div><div class="gt">Group {L}</div></div><ul>{lis}</ul></a>'
    out = head(f"{SITE} — 2026 World Cup AI Predictions for all 104 matches", DESC, canon="") + f"""
<section class="hero"><div class="wrap">
<div class="kicker"><span class="dot"></span>June 11, 2026 · Opening Day · USA · Canada · Mexico</div>
<h1 class="disp">2026 World Cup<br><em>AI Predictions</em></h1>
<p class="sub">The first 48-team World Cup. 104 matches. We run a data model on <b>every fixture</b> — score predictions, win probabilities and analysis. Know before kickoff.</p>
{accuracy_strip()}
<a class="opener" href="{murl(opener)}">
<div class="team"><div class="name">{esc(opener['home'])}</div><div class="meta">{esc(opener['venue'])}</div></div>
<div><div class="vs">VS</div><div class="score">{esc(op.get('score','-'))}</div></div>
<div class="team"><div class="name">{esc(opener['away'])}</div><div class="meta">{fmt_date(opener['date'])} · Opener</div></div>
</a>
<div class="tag">FIFA 2026</div>
</div></section>
<div class="wrap">{ad()}</div>
<section id="upcoming"><div class="wrap">
<div class="sec-head"><span class="idx">01</span><h2 class="disp">Upcoming Predictions</h2><div class="line"></div></div>
<div class="matches">{"".join(match_card(m) for m in upcoming)}</div>
</div></section>
<section id="groups"><div class="wrap">
<div class="sec-head"><span class="idx">02</span><h2 class="disp">Groups A–L</h2><div class="line"></div></div>
<div class="groups">{groups_html}</div>
</div></section>
<div class="wrap">{ad()}</div>
<section id="fixtures"><div class="wrap">
<div class="sec-head"><span class="idx">03</span><h2 class="disp">All Group Fixtures</h2><div class="line"></div></div>
<div class="matches">{"".join(match_card(m) for m in ALL)}</div>
</div></section>
""" + foot()
    open(os.path.join(DIST,"index.html"),"w",encoding="utf-8").write(out)

def build_group(L):
    g=DATA[L]
    teams_html="".join(f'<li><span class="seed">{i+1}</span>{esc(t["en"])}</li>' for i,t in enumerate(g["teams"]))
    title=f"Group {L} — {', '.join(t['en'] for t in g['teams'])} | 2026 World Cup Predictions"
    desc=f"2026 World Cup Group {L}: {', '.join(t['en'] for t in g['teams'])}. All 6 fixtures with AI score predictions and win probabilities."
    out=head(title,desc,rel="../",canon=f"group/{L}.html")+f"""
<div class="wrap"><div class="crumb"><a href="../index.html">Home</a> / <a href="../index.html#groups">Groups</a> / Group {L}</div></div>
<section class="detail-hero"><div class="wrap">
<div class="grp">Group {L} · Group Stage</div>
<h1 class="disp" style="font-size:clamp(40px,8vw,80px);margin-top:8px">Group {L}</h1>
<div class="groups" style="margin-top:24px;grid-template-columns:1fr"><div class="gcard"><ul>{teams_html}</ul></div></div>
</div></section>
<div class="wrap">{ad()}</div>
<section><div class="wrap">
{standings_table(g)}
<div class="sec-head"><span class="idx">VS</span><h2 class="disp">Group {L} · 6 Predictions</h2><div class="line"></div></div>
<div class="matches">{"".join(match_card(m, rel="../") for m in g["matches"])}</div>
</div></section>
""" + foot("../")
    open(os.path.join(DIST,"group",f"{L}.html"),"w",encoding="utf-8").write(out)

def build_static(slug, title, body_html):
    out = head(f"{title} | {SITE}", f"{title} — OracleXI 2026 World Cup AI predictions.", canon=f"{slug}.html") + f"""
<div class="wrap"><div class="crumb"><a href="index.html">Home</a> / {esc(title)}</div></div>
<section><div class="wrap" style="max-width:760px">
<div class="sec-head"><span class="idx">i</span><h2 class="disp">{esc(title)}</h2><div class="line"></div></div>
<div class="analysis-box" style="border-left-color:var(--gold)">{body_html}</div>
</div></section>
""" + foot()
    open(os.path.join(DIST, f"{slug}.html"), "w", encoding="utf-8").write(out)

ABOUT_HTML = """<p>OracleXI provides data-driven AI predictions for every match of the 2026 FIFA World Cup — score forecasts, win/draw/loss probabilities and concise analysis for all 104 fixtures across the 12 groups.</p>
<p>Our predictions are produced by a language model that weighs public information such as recent form, FIFA rankings, head-to-head records and playing styles. Results pages update automatically as matches are played, and we track how accurate the model is over time.</p>
<p>OracleXI is an independent project for football fans and is not affiliated with FIFA. Predictions are for entertainment and informational purposes only and are not betting advice.</p>"""

PRIVACY_HTML = """<p><b>Last updated: June 2026.</b></p>
<p>This Privacy Policy explains how OracleXI ("we", "us") handles information when you visit oraclexi.com.</p>
<p><b>Information we collect.</b> We do not ask you to create an account or submit personal data. Standard server and analytics logs may record non-identifying technical data such as browser type, device and pages visited.</p>
<p><b>Cookies and advertising.</b> We may display ads served by third-party vendors, including Google. Third-party vendors, including Google, use cookies to serve ads based on your prior visits to this and other websites. Google's use of advertising cookies enables it and its partners to serve ads to you based on your visits to our site and/or other sites on the Internet. You may opt out of personalized advertising by visiting <a href="https://www.google.com/settings/ads" style="color:var(--lime)">Google Ads Settings</a>. You can also opt out of third-party vendor cookies at <a href="https://www.aboutads.info" style="color:var(--lime)">www.aboutads.info</a>.</p>
<p><b>Third-party links.</b> Our site may link to external sites whose privacy practices we do not control.</p>
<p><b>Children.</b> This site is not directed at children under 13.</p>
<p><b>Contact.</b> Questions about this policy can be sent via the channels listed on our About page.</p>"""

def build_match(m):
    p=P(m); w,d,l=probs(m)
    title=f"{m['home']} vs {m['away']} Prediction: {p.get('score','-')} | 2026 World Cup Group {m['group']}"
    desc=f"{m['home']} vs {m['away']} prediction (2026 World Cup, Group {m['group']}): AI tips {p.get('score','-')}. Win probabilities {w:.0f}%/{d:.0f}%/{l:.0f}%. {(p.get('analysis') or '')[:70]}"
    out=head(title,desc,rel="../",canon=murl(m))+f"""
<div class="wrap"><div class="crumb"><a href="../index.html">Home</a> / <a href="../group/{m['group']}.html">Group {m['group']}</a> / {esc(m['home'])} vs {esc(m['away'])}</div></div>
<section class="detail-hero"><div class="wrap">
<div class="grp">Group {m['group']} · Match {m.get('match_no','')} · {fmt_date(m['date'])}</div>
<div class="vs-row"><div class="name">{esc(m['home'])}</div><div><div class="vs">VS</div><div class="pscore">{esc(p.get('score','-'))}</div></div><div class="name">{esc(m['away'])}</div></div>
<div class="meta-row"><span>🏟 <b>{esc(m['venue'] or 'TBD')}</b></span><span>⭐ Watch: <b>{esc(p.get('star') or '—')}</b></span></div>
</div></section>
<div class="wrap">
{ad()}
<div class="prob-big">
<div class="p win"><div class="v">{w:.0f}%</div><div class="k">{esc(m['home'])} win</div></div>
<div class="p draw"><div class="v">{d:.0f}%</div><div class="k">Draw</div></div>
<div class="p lose"><div class="v">{l:.0f}%</div><div class="k">{esc(m['away'])} win</div></div>
</div>
<div class="analysis-box"><div class="lbl">AI Match Analysis</div>{esc(p.get('analysis') or 'Analysis coming soon.')}</div>
<div class="disclaimer">⚠️ Predictions are generated by an AI model from historical and public data, for entertainment and informational purposes only. Not betting advice.</div>
{ad()}
</div>
""" + foot("../")
    open(os.path.join(DIST,"match",f"{mslug(m)}.html"),"w",encoding="utf-8").write(out)

def main():
    if os.path.exists(DIST):
        for n in os.listdir(DIST):
            if n==".git": continue
            pth=os.path.join(DIST,n); shutil.rmtree(pth) if os.path.isdir(pth) else os.remove(pth)
    else: os.makedirs(DIST)
    os.makedirs(os.path.join(DIST,"group"),exist_ok=True)
    os.makedirs(os.path.join(DIST,"match"),exist_ok=True)
    shutil.copy(os.path.join(ROOT,"static","style.css"),os.path.join(DIST,"style.css"))
    open(os.path.join(DIST,"favicon.svg"),"w").write('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#d4ff2e"/><text x="32" y="45" font-family="Arial Black,Arial" font-weight="900" font-size="26" fill="#0a0b0d" text-anchor="middle">XI</text></svg>')
    keyf = os.path.join(ROOT, ".indexnow_key")
    if os.path.exists(keyf):
        k = open(keyf).read().strip()
        open(os.path.join(DIST, f"{k}.txt"), "w").write(k)
    build_index()
    build_static("about", "About OracleXI", ABOUT_HTML)
    build_static("privacy", "Privacy Policy", PRIVACY_HTML)
    for L in "ABCDEFGHIJKL": build_group(L)
    for m in ALL: build_match(m)
    urls=["index.html","about.html","privacy.html"]+[f"group/{L}.html" for L in "ABCDEFGHIJKL"]+[murl(m) for m in ALL]
    sm='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    sm+="".join(f"<url><loc>{BASE}/{u}</loc></url>\n" for u in urls)+"</urlset>"
    open(os.path.join(DIST,"sitemap.xml"),"w").write(sm)
    open(os.path.join(DIST,"robots.txt"),"w").write(f"User-agent: *\nAllow: /\nSitemap: {BASE}/sitemap.xml\n")
    if ADSENSE_PUB:
        pub = ADSENSE_PUB.replace("ca-", "")
        open(os.path.join(DIST,"ads.txt"),"w").write(f"google.com, {pub}, DIRECT, f08c47fec0942fa0\n")
    print(f"✅ Built {2+12+len(ALL)} pages (English){' + AdSense' if ADSENSE_PUB else ''}")

if __name__=="__main__":
    main()
